_defaults:
  - "_rollout_reset_frq_4_w_offset.yml"
num_workers: 2
prefetch_factor: 1
pin_memory: false
model:
  spatial_config:
    first_drop_pattern: "1in2"
    rollout_keep_ratio: 0.45
    rollout_bg_samples_ratio: 0.16666
config_uniq_name: "rollout_reset_frq_4_w_offset_fg_180_bg_016"

