vanilla: true
model:
  drop_using_rollout: true
  backbone_config:
    token_drop: true
    drop_block_indices: [0]
    rollout_head_fusion: "root_mean_squares"
    rollout_block_indices: [0]
    rollout_reset_frq: 8
    first_frame_prune_disable: true
    first_drop_pattern: "1in4"
    block_class: "TokenwisePrunedBlock"
    windowed_class: "TokenwisePrunedBlock"
    first_block_class: "Block"
    output_buffer: true
    reset_full_process: true
    rollout_by_bbox: true
    rollout_bbox_score_thr: 0.1
    rollout_fg_samples_ratio: 1.0
    rollout_bg_samples_ratio: 0.0
    rollout_pool_size: 2
    max_local_offset: 1
    offset_using_patch_embed: true
